# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        7,
        _('Departments'),
        ['lineasDepto'],
        [],
[
    (_('Artigas'), _("It's easy")),
    (_('Salto'), _("It's easy")),
    (_('Paysandú'), _("It's easy")),
    (_('Río Negro'), _("It's easy")),
    (_('Rivera'), _("It's easy")),
    (_('Tacuarembó'), _("It's easy")),
    (_('Soriano'), _("It's easy")),
    (_('Colonia'), _("It's easy")),
    (_('Florida'), _("It's easy")),
    (_('Flores'), _("It's easy")),
    (_('San José'), _("It's easy")),
    (_('Durazno'), _("It's easy")),
    (_('Treinta y Tres'), _("It's easy")),
    (_('Cerro Largo'), _("It's easy")),
    (_('Rocha'), _("It's easy")),
    (_('Lavalleja'), _("It's easy")),
    (_('Maldonado'), _("It's easy")),
    (_('Canelones'), _("It's easy")),
    (_('Montevideo'), _("It's easy"))
]
]

LEVEL2 = [
        2,
        _('Departmental capitals'),
        ['lineasDepto', 'capitales'],
        [],
[
    (_('Artigas'), _("It's easy")),
    (_('Salto'), _("It's easy")),
    (_('Paysandú'), _("It's easy")),
    (_('Fray Bentos'), _("It's easy")),
    (_('Rivera'), _("It's easy")),
    (_('Tacuarembó'), _("It's easy")),
    (_('Mercedes'), _("It's easy")),
    (_('Colonia del Sacramento'), _("It's easy")),
    (_('Florida'), _("It's easy")),
    (_('Trinidad'), _("It's easy")),
    (_('San José de Mayo'), _("It's easy")),
    (_('Durazno'), _("It's easy")),
    (_('Treinta y Tres'), _("It's easy")),
    (_('Melo'), _("It's easy")),
    (_('Rocha'), _("It's easy")),
    (_('Minas'), _("It's easy")),
    (_('Maldonado'), _("It's easy")),
    (_('Canelones'), _("It's easy")),
    (_('Montevideo'), _("It's easy"))
]
]

LEVEL3 = [
        2,
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
    (_('Aiguá'), _("It's in %s") % _("Maldonado")),
    (_('Ansina'), _("It's in %s") % _("Tacuarembo")),
    (_('Artigas'), _("It's easy")),
    (_('Atlántida'), _("It's in %s") % _("Canelones")),
    (_('Baltasar Brum'), _("It's in %s") % _("Artigas")),
    (_('Bella Unión'), _('Is north')),
    (_('Belén'), _("It's in %s") % _("Salto")),
    (_('Canelones'), _("It's easy")),
    (_('Cardona'), _("It's in %s") % _("Soriano")),
    (_('Carmelo'), _("It's in %s") % _("Colonia")),
    (_('Castillos'), _("It's in %s") % _("Rocha")),
    (_('Casupá'), _("It's in %s") % _("Florida")),
    (_('Cebollatí'), _("It's in %s") % _("Rocha")),
    (_('Cerro Chato'), _("It's in %s") % _("Treinta y Tres")),
    (_('Chuy'), _("It's near Brazil")),
    (_('Colonia del Sacramento'), _('Try again')),
    (_('Constitución'), _("It's in %s") % _("Salto")),
    (_('Dolores'), _("It's in %s") % _("Soriano")),
    (_('Durazno'), _("It's in %s") % _("the center")),
    (_('Florida'), _("It's easy")),
    (_('Fraile Muerto'), _("It's in %s") % _("Cerro Largo")),
    (_('Fray Bentos'), _("It's in %s") % _("Rio Negro")),
    (_('Guichón'), _("It's in %s") % _("Paysandu")),
    (_('J. Batlle y Ordóñez'), _("It's in %s") % _("Lavalleja")),
    (_('J. Pedro Varela'), _("It's in %s") % _("Lavalleja")),
    (_('José E. Rodó'), _("It's in %s") % _("Soriano")),
    (_('Juan Lacaze'), _("It's in %s") % _("Colonia")),
    (_('La Coronilla'), _("It's in %s") % _("Rocha")),
    (_('La Paloma'), _("It's in %s") % _("Rocha")),
    (_('Las Piedras'), _("It's in %s") % _("Canelones")),
    (_('Lascano'), _("It's in %s") % _("Rocha")),
    (_('Libertad'), _("It's in %s") % _("San José")),
    (_('Maldonado'), _("It's easy")),
    (_('Melo'), _("It's a departmental capital")),
    (_('Mercedes'), _("It's a departmental capital")),
    (_('Minas'), _("It's a departmental capital")),
    (_('Minas de Corrales'), _("It's in %s") % _("Rivera")),
    (_('Montevideo'), _("It's easy")),
    (_('Nueva Helvecia'), _("It's in %s") % _("Colonia")),
    (_('Nueva Palmira'), _("It's in %s") % _("Colonia")),
    (_('Nuevo Berlín'), _("It's in %s") % _("Rio Negro")),
    (_('Ombúes de Lavalle'), _("It's in %s") % _("Colonia")),
    (_('Palmitas'), _("It's in %s") % _("Soriano")),
    (_('Pan de Azúcar'), _("It's in %s") % _("Maldonado")),
    (_('Pando'), _("It's in %s") % _("Canelones")),
    (_('Paso de los Toros'), _("It's in %s") % _("Tacuarembo")),
    (_('Paysandú'), _("It's easy")),
    (_('Piriápolis'), _("It's in %s") % _("Maldonado")),
    (_('Pueblo del Carmen'), _("It's in %s") % _("Durazno")),
    (_('Punta del Este'), _("It's in %s") % _("Maldonado")),
    (_('Quebracho'), _("It's in %s") % _("Paysandu")),
    (_('Rivera'), _("It's near Brazil")),
    (_('Rocha'), _("It's a departmental capital")),
    (_('Rosario'), _("It's in %s") % _("Colonia")),
    (_('Río Branco'), _("It's in %s") % _("Cerro Largo")),
    (_('Salto'), _("It's easy")),
    (_('San Carlos'), _("It's in %s") % _("Maldonado")),
    (_('San Gregorio de Polanco'), _("It's in %s") % _("Tacuarembo")),
    (_('San José de Mayo'), _("It's a departmental capital")),
    (_('San Ramón'), _("It's in %s") % _("Canelones")),
    (_('Santa Clara de Olimar'), _("It's in %s") % _("Treinta y Tres")),
    (_('Santa Lucía'), _("It's in %s") % _("Canelones")),
    (_('Sarandí del Yi'), _("It's in %s") % _("Durazno")),
    (_('Sarandí Grande'), _("Queda en Florida")),
    (_('Tacuarembó'), _("It's easy")),
    (_('Tala'), _("It's in %s") % _("Canelones")),
    (_('Tarariras'), _("It's in %s") % _("Colonia")),
    (_('Tomás Gomensoro'), _("It's in %s") % _("Artigas")),
    (_('Tranqueras'), _("It's in %s") % _("Rivera")),
    (_('Treinta y Tres'), _("It's a departmental capital")),
    (_('Trinidad'), _("It's a departmental capital")),
    (_('Vergara'), _("It's in %s") % _("Treinta y Tres")),
    (_('Vichadero'), _("It's in %s") % _("Rivera")),
    (_('Young'), _("It's in %s") % _("Rio Negro"))
]
]

LEVEL4 = [
        4,
        _('Waterways'),
        ['lineasDepto', 'rios'],
        [],
[
    (_('Arapey Chico River'), _('Is north')),
    (_('Arapey Grande River'), _('Flows in the Uruguay River')),
    (_('Cebollatí River'), _('Flows in the Merin Lagoon')),
    (_('Cuareim River'), _('Is north')),
    (_('Daymán River'), _('Flows in the Uruguay River')),
    (_('Negro River'), _('Has three dams')),
    (_('Olimar Chico River'), _("It's in %s") % _("Treinta y Tres")),
    (_('Olimar Grande River'), _("It's in %s") % _("Treinta y Tres")),
    (_('Queguay Chico River'), _("It's in %s") % _("Paysandu")),
    (_('Queguay River'), _('Flows in the Uruguay River')),
    (_('Rosario River'), _("It's in %s") % _("Colonia")),
    (_('San José River'), _("It's in %s") % _("San José")),
    (_('San Juan River'), _("It's in %s") % _("Colonia")),
    (_('San Salvador River'), _("It's in %s") % _("Soriano")),
    (_('Santa Lucía River'), _("It's easy")),
    (_('Sta Lucía Chico River'), _("It's in %s") % _("Canelones")),
    (_('Tacuarembo River'), _("It's in %s") % _("Tacuarembo")),
    (_('Tacuarí River'), _('Flows in the Merin Lagoon')),
    (_('Uruguay River'), _("It's easy")),
    (_('Yaguarón River'), _("It's near Brazil")),
    (_('Yi River'), _("It's in %s") % _("Durazno")),
    (_('Río de la Plata'), _("It's easy")),
    (_('Atlantic Ocean'), _("It's easy")),
    (_('Merín Lagoon'), _("Is east")),
    (_('Negra Lagoon'), _("It's in %s") % _("Rocha")),
    (_('Castillos Lagoon'), _("It's in %s") % _("Rocha")),
    (_('Rocha Lagoon'), _("It's in %s") % _("Rocha")),
    (_('Sauce Lagoon'), _("It's in %s") % _("Maldonado"))
]
]

LEVEL5 = [
        1,
        _('Elevations'),
        ['cuchillas', 'cerros'],
        [],
[
    (_('the %s') % _('Cuchilla de Haedo'), 4, _('Cuchilla de Haedo'), _('Queda al norte')),
    (_('the %s') % _('Cuchilla Negra'), 4, _('Cuchilla Negra'), _('Queda en el límite con Brasil')),
    (_('the %s') % _('Cuchilla de Santa Ana'), 4, _('Cuchilla de Santa Ana'), _('Queda en Rivera')),
    (_('the %s') % _('Cuchilla Grande'), 4, _('Cuchilla Grande'), _('Queda en el sur')),
    (_('the %s') % _('Cuchilla Grande del Durazno'), 4, _('Cuchilla Grande del Durazno'), _('Queda en Durazno')),
    (_('the %s') % _('Cuchilla Grande Inferior'), 4, _('Cuchilla Grande Inferior'), _('Va de Lavalleja a Colonia')),
    (_('the %s') % _('Cerro de Montevideo'), 5, _('Cerro de Montevideo'), _('Queda en Montevideo')),
    (_('the %s') % _('Cerro Pan de Azúcar'), 5, _('Cerro Pan de Azúcar'), _('Queda en Maldonado')),
    (_('the %s') % _('Cerro Verdún'), 5, _('Cerro Verdún'), _('Queda en Lavalleja')),
    (_('the %s') % _('Cerro Arequita'), 5, _('Cerro Arequita'), _('Queda en Lavalleja')),
    (_('the %s') % _('Cerro Catedral'), 5, _('Cerro Catedral'), _('Queda en Maldonado')),
    (_('the %s') % _('Cerro de las Animas'), 5, _('Cerro de las Animas'), _('Queda en Maldonado')),
    (_('the %s') % _('Cerros de Batoví'), 5, _('Cerros de Batoví'), _('Quedan en el norte')),
    (_('the %s') % _('Cerro Bonito'), 5, _('Cerro Bonito'), _('Queda en la Cuchilla de Santa Ana')),
    (_('the %s') % _('Cerro del Medio'), 5, _('Cerro del Medio'), _('Queda en Tacuarembó')),
    (_('the %s') % _('Cerro Chato'), 5, _('Cerro Chato'), _('Queda en Durazno'))
]
]

LEVEL6 = [
        5,
        _('Routes'),
        ['rutas', 'capitales'],
        ['capitales'],
[
    (_('Route %s') % 1, _('Va de Montevideo\na Colonia')),
    (_('Route %s') % 2, _('Pasa por Mercedes')),
    (_('Route %s') % 3, _('Va por el litoral')),
    (_('Route %s') % 4, _('Está en el norte')),
    (_('Route %s') % 5, _('Va de Montevideo\na Rivera')),
    (_('Route %s') % 6, _('Va hasta Vichadero')),
    (_('Route %s') % 7, _('Pasa por Melo')),
    (_('Route %s') % 8, _('Pasa por Minas')),
    (_('Route %s') % 9, _('Pasa por Rocha')),
    (_('Route %s') % 21, _('Recorre el litoral\nde Colonia')),
    (_('Route %s') % 11, _('Pasa por San José\ny Canelones')),
    (_('Route %s') % 14, _('Va de Mercedes a\nLa Coronilla')),
    (_('Route %s') % 26, _('Pasa por Tacuarembó')),
    (_('Route %s') % 'Interbalnearia', _('Pasa por Punta del Este'))
]
]

LEVELS = [LEVEL1, LEVEL2, LEVEL3, LEVEL4, LEVEL5, LEVEL6]

