# -*- coding: utf-8 -*-

from gettext import gettext as _

LEVEL1 = [
        7,
        _('Departments'),
        ['lineasDepto'],
        [],
[
    (_('Artigas'), _("It's easy")),
    (_('Salto'), _("It's easy")),
    (_('Paysandú'), _("It's easy")),
    (_('Río Negro'), _("It's easy")),
    (_('Rivera'), _("It's easy")),
    (_('Tacuarembó'), _("It's easy")),
    (_('Soriano'), _("It's easy")),
    (_('Colonia'), _("It's easy")),
    (_('Florida'), _("It's easy")),
    (_('Flores'), _("It's easy")),
    (_('San José'), _("It's easy")),
    (_('Durazno'), _("It's easy")),
    (_('Treinta y Tres'), _("It's easy")),
    (_('Cerro Largo'), _("It's easy")),
    (_('Rocha'), _("It's easy")),
    (_('Lavalleja'), _("It's easy")),
    (_('Maldonado'), _("It's easy")),
    (_('Canelones'), _("It's easy")),
    (_('Montevideo'), _("It's easy"))
]
]

LEVEL2 = [
        2,
        _('Departmental capitals'),
        ['lineasDepto', 'capitales'],
        [],
[
    (_('Artigas'), _("It's easy")),
    (_('Salto'), _("It's easy")),
    (_('Paysandú'), _("It's easy")),
    (_('Fray Bentos'), _("It's easy")),
    (_('Rivera'), _("It's easy")),
    (_('Tacuarembó'), _("It's easy")),
    (_('Mercedes'), _("It's easy")),
    (_('Colonia del Sacramento'), _("It's easy")),
    (_('Florida'), _("It's easy")),
    (_('Trinidad'), _("It's easy")),
    (_('San José de Mayo'), _("It's easy")),
    (_('Durazno'), _("It's easy")),
    (_('Treinta y Tres'), _("It's easy")),
    (_('Melo'), _("It's easy")),
    (_('Rocha'), _("It's easy")),
    (_('Minas'), _("It's easy")),
    (_('Maldonado'), _("It's easy")),
    (_('Canelones'), _("It's easy")),
    (_('Montevideo'), _("It's easy"))
]
]

LEVEL3 = [
        2,
        _('Cities'),
        ['lineasDepto', 'capitales', 'ciudades'],
        [],
[
    (_('Aiguá'), _("It's in %s") % _("Maldonado")),
    (_('Ansina'), _("It's in %s") % _("Tacuarembó")),
    (_('Artigas'), _("It's easy")),
    (_('Atlántida'), _("It's in %s") % _("Canelones")),
    (_('Baltasar Brum'), _("It's in %s") % _("Artigas")),
    (_('Bella Unión'), _('Is north')),
    (_('Belén'), _("It's in %s") % _("Salto")),
    (_('Canelones'), _("It's easy")),
    (_('Cardona'), _("It's in %s") % _("Soriano")),
    (_('Carmelo'), _("It's in %s") % _("Colonia")),
    (_('Castillos'), _("It's in %s") % _("Rocha")),
    (_('Casupá'), _("It's in %s") % _("Florida")),
    (_('Cebollatí'), _("It's in %s") % _("Rocha")),
    (_('Cerro Chato'), _("It's in %s") % _("Treinta y Tres")),
    (_('Chuy'), _("It's near Brazil")),
    (_('Colonia del Sacramento'), _('Try again')),
    (_('Constitución'), _("It's in %s") % _("Salto")),
    (_('Dolores'), _("It's in %s") % _("Soriano")),
    (_('Durazno'), _("It's in %s") % _("the center")),
    (_('Florida'), _("It's easy")),
    (_('Fraile Muerto'), _("It's in %s") % _("Cerro Largo")),
    (_('Fray Bentos'), _("It's in %s") % _("Rio Negro")),
    (_('Guichón'), _("It's in %s") % _("Paysandú")),
    (_('José Batlle y Ordóñez'), _("It's in %s") % _("Lavalleja")),
    (_('José Pedro Varela'), _("It's in %s") % _("Lavalleja")),
    (_('José Enrique Rodó'), _("It's in %s") % _("Soriano")),
    (_('Juan Lacaze'), _("It's in %s") % _("Colonia")),
    (_('La Coronilla'), _("It's in %s") % _("Rocha")),
    (_('La Paloma'), _("It's in %s") % _("Rocha")),
    (_('Las Piedras'), _("It's in %s") % _("Canelones")),
    (_('Lascano'), _("It's in %s") % _("Rocha")),
    (_('Libertad'), _("It's in %s") % _("San José")),
    (_('Maldonado'), _("It's easy")),
    (_('Melo'), _("It's the capital of\nthe department")),
    (_('Mercedes'), _("It's the capital of\nthe department")),
    (_('Minas'), _("It's the capital of\nthe department")),
    (_('Minas de Corrales'), _("It's in %s") % _("Rivera")),
    (_('Montevideo'), _("It's easy")),
    (_('Nueva Helvecia'), _("It's in %s") % _("Colonia")),
    (_('Nueva Palmira'), _("It's in %s") % _("Colonia")),
    (_('Nuevo Berlín'), _("It's in %s") % _("Rio Negro")),
    (_('Ombúes de Lavalle'), _("It's in %s") % _("Colonia")),
    (_('Palmitas'), _("It's in %s") % _("Soriano")),
    (_('Pan de Azúcar'), _("It's in %s") % _("Maldonado")),
    (_('Pando'), _("It's in %s") % _("Canelones")),
    (_('Paso de los Toros'), _("It's in %s") % _("Tacuarembó")),
    (_('Paysandú'), _("It's easy")),
    (_('Piriápolis'), _("It's in %s") % _("Maldonado")),
    (_('Pueblo del Carmen'), _("It's in %s") % _("Durazno")),
    (_('Punta del Este'), _("It's in %s") % _("Maldonado")),
    (_('Quebracho'), _("It's in %s") % _("Paysandú")),
    (_('Rivera'), _("It's near Brazil")),
    (_('Rocha'), _("It's the capital of\nthe department")),
    (_('Rosario'), _("It's in %s") % _("Colonia")),
    (_('Río Branco'), _("It's in %s") % _("Cerro Largo")),
    (_('Salto'), _("It's easy")),
    (_('San Carlos'), _("It's in %s") % _("Maldonado")),
    (_('San Gregorio de Polanco'), _("It's in %s") % _("Tacuarembó")),
    (_('San José de Mayo'), _("It's the capital of\nthe department")),
    (_('San Ramón'), _("It's in %s") % _("Canelones")),
    (_('Santa Clara de Olimar'), _("It's in %s") % _("Treinta y Tres")),
    (_('Santa Lucía'), _("It's in %s") % _("Canelones")),
    (_('Sarandí del Yi'), _("It's in %s") % _("Durazno")),
    (_('Sarandí Grande'), _("It's in %s") % _("Florida")),
    (_('Tacuarembó'), _("It's easy")),
    (_('Tala'), _("It's in %s") % _("Canelones")),
    (_('Tarariras'), _("It's in %s") % _("Colonia")),
    (_('Tomás Gomensoro'), _("It's in %s") % _("Artigas")),
    (_('Tranqueras'), _("It's in %s") % _("Rivera")),
    (_('Treinta y Tres'), _("It's the capital of\nthe department")),
    (_('Trinidad'), _("It's the capital of\nthe department")),
    (_('Vergara'), _("It's in %s") % _("Treinta y Tres")),
    (_('Vichadero'), _("It's in %s") % _("Rivera")),
    (_('Young'), _("It's in %s") % _("Rio Negro"))
]
]

LEVEL4 = [
        15,
        _('Waterways'),
        ['lineasDepto', 'rios'],
        [],
[
    (_('Río Arapey Chico'), _('Is north')),
    (_('Río Arapey Grande'), _('Flows into the %s') % _('Uruguay')),
    (_('Río Cebollatí'), _('Flows into the %s') % _('Laguna Merín')),
    (_('Río Cuareim'), _('Is north')),
    (_('Río Daymán'), _('Flows into the %s') % _('Uruguay')),
    (_('Río Negro'), _('Has three dams')),
    (_('Río Olimar Chico'), _("It's in %s") % _("Treinta y Tres")),
    (_('Río Olimar Grande'), _("It's in %s") % _("Treinta y Tres")),
    (_('Río Queguay Chico'), _("It's in %s") % _("Paysandú")),
    (_('Río Queguay'), _('Flows into the %s') % _('Uruguay')),
    (_('Río Rosario'), _("It's in %s") % _("Colonia")),
    (_('Río San José'), _("It's in %s") % _("San José")),
    (_('Río San Juan'), _("It's in %s") % _("Colonia")),
    (_('Río San Salvador'), _("It's in %s") % _("Soriano")),
    (_('Río Santa Lucía'), _("It's easy")),
    (_('Río Santa Lucía Chico'), _("It's in %s") % _("Canelones")),
    (_('Río Tacuarembó'), _("It's in %s") % _("Tacuarembó")),
    (_('Río Tacuarí'),  _('Flows into the %s') % _('Laguna Merín')),
    (_('Río Uruguay'), _("It's easy")),
    (_('Río Yaguarón'), _("It's near Brazil")),
    (_('Río Yi'), _("It's in %s") % _("Durazno")),
    (_('Río de la Plata'), _("It's easy")),
    (_('Atlantic Ocean'), _("It's easy")),
    (_('Laguna Merín'), _("It's in the east")),
    (_('Laguna Negra'), _("It's in %s") % _("Rocha")),
    (_('Laguna de Castillos'), _("It's in %s") % _("Rocha")),
    (_('Laguna de Rocha'), _("It's in %s") % _("Rocha")),
    (_('Laguna del Sauce'), _("It's in %s") % _("Maldonado"))
]
]

LEVEL5 = [
        1,
        _('Elevations'),
        ['cuchillas', 'cerros'],
        [],
[
    (_('the %s') % _('Cuchilla de Haedo'), 4, _('Cuchilla de Haedo'), _("It's in the north")),
    (_('the %s') % _('Cuchilla Negra'), 4, _('Cuchilla Negra'), _("It's on the border\nwith %s") % _('Brasil')),
    (_('the %s') % _('Cuchilla de Santa Ana'), 4, _('Cuchilla de Santa Ana'), _("It's in %s") % _('Rivera')),
    (_('the %s') % _('Cuchilla Grande'), 4, _('Cuchilla Grande'), _("It's in the south")),
    (_('the %s') % _('Cuchilla Grande del Durazno'), 4, _('Cuchilla Grande del Durazno'), _("It's in %s") % _('Durazno')),
    (_('the %s') % _('Cuchilla Grande Inferior'), 4, _('Cuchilla Grande Inferior'), _('Try again')),
    (_('the %s') % _('Cerro de Montevideo'), 5, _('Cerro de Montevideo'), _("It's in %s") % _('Montevideo')),
    (_('the %s') % _('Cerro Pan de Azúcar'), 5, _('Cerro Pan de Azúcar'), _("It's in %s") % _('Maldonado')),
    (_('the %s') % _('Cerro Verdún'), 5, _('Cerro Verdún'), _("It's in %s") % _('Lavalleja')),
    (_('the %s') % _('Cerro Arequita'), 5, _('Cerro Arequita'), _("It's in %s") % _('Lavalleja')),
    (_('the %s') % _('Cerro Catedral'), 5, _('Cerro Catedral'), _("It's in %s") % _('Maldonado')),
    (_('the %s') % _('Cerro de las Animas'), 5, _('Cerro de las Animas'), _("It's in %s") % _('Maldonado')),
    (_('the %s') % _('Cerros de Batoví'), 5, _('Cerros de Batoví'), _("It's in the north")),
    (_('the %s') % _('Cerro Bonito'), 5, _('Cerro Bonito'), _("It's in %s") % _('Cuchilla de Santa Ana')),
    (_('the %s') % _('Cerro del Medio'), 5, _('Cerro del Medio'), _("It's in %s") % _('Tacuarembó')),
    (_('the %s') % _('Cerro Chato'), 5, _('Cerro Chato'), _("It's in %s") % _('Durazno'))
]
]

LEVEL6 = [
        5,
        _('Routes'),
        ['rutas', 'capitales'],
        ['capitales'],
[
    (_('Route %s') % 1, _('Try again')),
    (_('Route %s') % 2, _('Passes through %s') % _('Mercedes')),
    (_('Route %s') % 3, _('Try again')),
    (_('Route %s') % 4, _("It's in the north")),
    (_('Route %s') % 5, _('Try again')),
    (_('Route %s') % 6, _("Ends in %s") % _('Vichadero')),
    (_('Route %s') % 7, _('Passes through %s') % _('Melo')),
    (_('Route %s') % 8, _('Passes through %s') % _('Minas')),
    (_('Route %s') % 9, _('Passes through %s') % _('Rocha')),
    (_('Route %s') % 21, _('Try again')),
    (_('Route %s') % 11, _('Passes through %s') % _('San José') + _('and') + _('Canelones')),
    (_('Route %s') % 14, _('Try again')),
    (_('Route %s') % 26, _('Passes through %s') % _('Tacuarembó')),
    (_('Route %s') % 'Interbalnearia', _('Passes through %s') % _('Punta del Este'))
]
]

LEVELS = [LEVEL1, LEVEL2, LEVEL3, LEVEL4, LEVEL5, LEVEL6]

